# https://docs.docker.com/compose/compose-file/

name: ComputerNetwork

services:
  web:
    image: caddy:2.9.1-alpine
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8888:8888
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
  app:
    build: .
    command: npm run start
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: mongo:8.0.5-rc2
    restart: always
    volumes:
      - computer_networks_project_db_data:/data/db
    env_file:
      - ./.env
volumes:
  computer_networks_project_db_data:
    external: true
  caddy_data:
    external: true
  caddy_config:
