# https://docs.docker.com/compose/compose-file/

name: ComputerNetwork

services:
  web:
    image: caddy:2.9.1-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
      - 8888:8888
      - 2019:2019
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mongo:8.0.5-rc2
    restart: always
    ports:
      - 27017:27017
    volumes:
      - computer_networks_project_db_data:/data/db
    env_file:
      - ./.env
volumes:
  computer_networks_project_db_data:
    external: true
  caddy_data:
    external: true
  caddy_config:
